In [1]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [12]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
dframe1=DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2=DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [15]:
dframe1

X         Y         Z
0 -0.712519 -0.142232 -0.938542
1 -0.966399  1.149578 -1.013664
2  0.407683 -0.150514 -0.728975
3  1.148449  1.431980 -0.842512

In [16]:
dframe2

Y         Q         X
0  0.884247 -0.768586  0.169701
1  0.157571  2.046712  1.310202
2 -0.880672  0.077474  0.929198

In [17]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0 -0.712519 -0.142232 -0.938542       NaN
1 -0.966399  1.149578 -1.013664       NaN
2  0.407683 -0.150514 -0.728975       NaN
3  1.148449  1.431980 -0.842512       NaN
0  0.169701  0.884247       NaN -0.768586
1  1.310202  0.157571       NaN  2.046712
2  0.929198 -0.880672       NaN  0.077474

In [18]:
pd.concat([dframe1,dframe2],ignore_index=True)

X         Y         Z         Q
0 -0.712519 -0.142232 -0.938542       NaN
1 -0.966399  1.149578 -1.013664       NaN
2  0.407683 -0.150514 -0.728975       NaN
3  1.148449  1.431980 -0.842512       NaN
4  0.169701  0.884247       NaN -0.768586
5  1.310202  0.157571       NaN  2.046712
6  0.929198 -0.880672       NaN  0.077474